# Generated by Django 2.2.4 on 2021-03-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
